### PR TITLE
EPE-139 Add code signing in Maven and update README.md

### PR DESCRIPTION
**Pull request by xwang2713**
Add extra step if want to run code signing through Maven. 
1) Set required variables in Maven configure file with profile "hpcc.sign", for example &lt;MAVEN  HOME&gt;/conf/settings.xml
2) Execute <b>mvn -P hpcc.sign jarsigner:sign</b>

@GordonSmith please review
Signed-off-by: Xiaoming Wang xiaoming.wang@lexisnexis.com

### CODE REVIEW

**Comment by GordonSmith** [comment]
This looks ok to me - but I am not qualified to look at the maven part.  Should be safe to pull.

**Comment by xwang2713** [comment]
@mjkrumlauf could you help to review? Thanks

**Comment by richardkchapman** [comment]
@xwang2713 Can you reach out to @mjkrumlauf to see if we can get this moved forwards...

**Comment by xwang2713** [comment]
Following is from @mjkrumlauf:
I perused the code and documentation changes.  I have never used the maven-jarsigner-plugin so I’m afraid I’m not much help here.  

I recommend that in the absence of an expert reviewer you find solutions to similar use cases and pattern your pom.xml modifications after them, which I am assuming that you have already done that.  If it works, go for it.




The sign code part is separated from main ECL Eclipse-Plugins build. It will not impact main ECL Eclipse-Plugins build. User can use sign.bat/sign.sh to sign the code as well.

**Comment by GordonSmith** [comment]
If this is building and working in Jenkins I would suggest pulling it is fine.

**Pull request merged**
